services:
  - type: web
    name: musify
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.0.0
      - key: JWT_SECRET
        generateValue: true